### ISSUE TITLE
Epic: Party Management

### ISSUE THREAD

**Issue by ScidaJ** [ScidaJ/DnDUtils#17]
As a user, I want to
- [ ] Create a new party
- [ ] View party information using the command `/get-party <partyName>`
- [ ] Add a user to the party with the command `/add-to-party <@userName> <partyName>`
- [ ] Remove a user from the party with the command `/remove-from-party <@userName> <partyName>` which can only be done by the owner of the party
- [ ] Transfer ownership of the party to another user with the command `/make-owner <@userName><party/itemName>`
- [ ] Delete the party with the command `/delete <party/itemName>` Send a Discord message asking for verification
