### ISSUE TITLE
Epic: Homebrew Item Management

### ISSUE THREAD

**Issue by ScidaJ** [ScidaJ/DnDUtils#19]
As a user,
- [ ] When I create a new Homebrew item, with the command `/create-item` there are other options to add, such as type, weight, and value, as well as if it is globally viewable
- [ ] I should be able to look up an item by its name/id, using the command `/item <itemName>`
- [ ] I should be able to transfer ownership of the item to a different user, with the command `/transfer-item/party <@userName>`, this will trigger a PM asking if this is correct, and can only be initiated by the owner
- [ ] I should be able to delete an item with the command `/delete-item <itemID>` this MUST be the item's ID, which is shown using the view command. This will also trigger a PM, and can only be done by the owner
